### PR TITLE
Adds ellipse, triangle and point annotations

### PR DESCRIPTION
**Pull request by stockiNail**
Adds new annotations type, like triangle, ellipse and point.
Adds `cornerRadius `options to box annotation in order to have  a rounded rectangle.

### CODE REVIEW

**Comment by kurkle** [comment]
Thanks!

Would it be ok for you to split this in multiple requests? Separate by shape and the `cornerRadius` in its own Would make reviewing easier.

**Comment by stockiNail** [comment]
> 
> 
> Thanks!
> 
> Would it be ok for you to split this in multiple requests? Separate by shape and the `cornerRadius` in its own. Would make reviewing easier.

Sorry, I missed your reply... Let me check what I can do it

**Comment by stockiNail** [comment]
@kurkle let me split the current PR in 3 (but tomorrow):

1. current PR with new shapes
2. add `cornerRadius` to the box annotation
3. fixes issue #264

Sorry I used only 1 PR.

**Comment by stockiNail** [comment]
@kurkle fixed scope of this PR with only new annotation shape.
 
Next 2 PRs will start from this one.

**Review by kurkle — APPROVED** [review]

**Pull request merged**
