### PR TITLE
Bump to version 2.0.0

### PR DESCRIPTION
**Pull request by stockiNail**

### CODE REVIEW

**Review by LeeLenaleee — DISMISSED** [review]

**Comment by stockiNail** [comment]
I have seen a warning from Vue-Press:

```log
[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.
```

The warnings sound to be related to `@simonbrunel/vuepress-plugin-versions` (file **/src/components/VersionsDropdown.vue**) and `vuepress-theme-chartjs`(file **/components/Tooltip.vue**)

**Comment by stockiNail** [comment]
> I have seen a warning from Vue-Press:
> 
> ```
> [@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.
> ```

Shall we wait for fix in the other projects?

**Comment by LeeLenaleee** [comment]
What if you just upp the version number and not the versions of the used packages

**Comment by stockiNail** [comment]
> What if you just upp the version number and not the versions of the used packages

It works. I rollback the the package-lock.json.

**Review by LeeLenaleee — APPROVED** [review]

**Comment by stockiNail** [comment]
I don't see any npm deployment and also the version is still in draft... Is it usual?

**Comment by kurkle** [comment]
Yes, you need to publish that release, which will trigger the npm publish.

**Comment by stockiNail** [comment]
oh... I was convinced that last time it was done automatically. I put it in my notes.

Thank you @kurkle

**Comment by LeeLenaleee** [comment]
@stockiNail you are not the only one, if you wanna know how to publish (took me some googling) go to the draft click the pencil on the top right to edit it then at the bottom you have a big green publish button

**Comment by stockiNail** [comment]
> @stockiNail you are not the only one, if you wanna know how to publish (took me some googling) go to the draft click the pencil on the top right to edit it then at the bottom you have a big green publish button

Thank you @LeeLenaleee !!! I know how to do it manually, having other projects where I'm doing that but I was convinced (dont ask me why) here it was all automated, triggered by Bump PR. And I was wondering how the deployment could start based on event of a merged specific PR.... Now it's clear! ;)

**Pull request merged**
