### PR TITLE
Fix `animations` option type and add missing documentation

### LINKED ISSUE #559: animations is not optional in types and is missing from documentation
Since this commit, I have the following error in my project (when I try to upgrade this library):
> error TS2741: Property 'animations' is missing in type '{ annotations: { [key: string]: AnnotationOptions<keyof AnnotationTypeRegistry>; }; }' but required in type 'AnnotationPluginOptions'.

Shouldn't the `animations` property be optional ?
```diff
- animations: Record<string, unknown>,
+ animations?: Record<string, unknown>,
```

I don't find any documentation on this property in https://www.chartjs.org/chartjs-plugin-annotation/latest/ ; am I missing something ?

Thanks!

_Originally posted by @jbelien in https://github.com/chartjs/chartjs-plugin-annotation/pull/448#discussion_r768806334_

### PR DESCRIPTION
**Pull request by stockiNail**
Fixes #559

### CODE REVIEW

**Review by kurkle — APPROVED** [review]

**Comment by kurkle** [comment]
Should pay some more attention to the commit messages :)

Screenshot_20211214-190333

**Comment by stockiNail** [comment]
@kurkle I didn't understand...

**Comment by kurkle** [comment]
It's the first commit message that gets suggested when merging. You can edit it at that point too.

**Comment by stockiNail** [comment]
> You can edit it at that point too.

Ok.. apologize.. but is it in the form opened when I'm merging? Because I can't see where what you reported is located.

**Comment by kurkle** [comment]
https://github.com/chartjs/chartjs-plugin-annotation/commits/master

Commit messages create the git history. Pull request description ends up in the release notes and is more important. But good commit messages are important too.

More information for example here: https://www.google.com/amp/s/cbea.ms/git-commit/amp/

**Comment by stockiNail** [comment]
Now it's clear. My fault is to commit the branch with the "fix [issue]" instead of the real title of the target PR in the project... Sorry.
Be patient

**Comment by kurkle** [comment]
Also don't worry too much about that, I'm not very good with the commit messages either.
Just pointing out its something that we should try to improve.

**Comment by stockiNail** [comment]
> Also don't worry too much about that, I'm not very good with the commit messages either. Just pointing out its something that we should try to improve.

Absolutely I'll do!

**Pull request merged**
