### PR TITLE
Upgrade dependencies and implementation of the integration test

### PR DESCRIPTION
**Pull request by stockiNail**
This PR is changing the dependency with CHART.JS, going to version4. It's also adding the test on TS 4.7.x

### CODE REVIEW

**Review by kurkle — COMMENTED** [review]
Maybe it should ve testing both?

**Comment by stockiNail** [comment]
> Maybe it should ve testing both?

Chart.js 3 and 4?

**Comment by kurkle** [comment]
Yes, or was v3 support already droped?

**Comment by stockiNail** [comment]
V3 should be supported, version 3.7.0

**Comment by stockiNail** [comment]
I will work tomorrow on that. I think we need a package.json template to update at runtime, settimg v3 and then v4. I need to see how the fs api in js are working

**Comment by kurkle** [comment]
Its already running for each of the ts versions, should not be hard to add another loop for that. Or just split to separate folders (and maybe test only some of the later ts versions with v4)

**Comment by stockiNail** [comment]
> Its already running for each of the ts versions, should not be hard to add another loop for that. Or just split to separate folders (and maybe test only some of the later ts versions with v4)

@kurkle I have done! Have a look if ok.
Let me say that the implementation is getting the devDep and peerDep of the plugin to chart.js and based on that it calculates the amount of majors between them. And then, configure the package.json for testing to use the last version in the major, by [major].x.x. 
In this way we don't have to change anything next time, when the plugin will change the dependencies to Chart.js

**Comment by stockiNail** [comment]
Must be rebased when #838 will be merged. Now in draft

**Comment by kurkle** [comment]
Many lines of code to avoid adding a chart.js major once a year or two? :)
Less maintenance is less maintenance, so why not.

**Comment by kurkle** [comment]
Another thought, maybe this one should be converted to pnpm too, so it could use workspace dependencies and avoid the temporary directory stuff. Like its done in chart.js now.

**Comment by stockiNail** [comment]
> Many lines of code to avoid adding a chart.js major once a year or two? :)
> Less maintenance is less maintenance, so why not.

I could agree. For my mindset, I'm never afraid about maintenance or LoC ;) 

> Another thought, maybe this one should be converted to pnpm too, so it could use workspace dependencies and avoid the temporary directory stuff. Like its done in chart.js now.

OK! for this one, I need more time to have a look how it works with more details that I have got now.

**Comment by stockiNail** [comment]
Close for now

**Pull request closed without merging**
