### PR TITLE
Chore/remove old samples

### PR DESCRIPTION
**Pull request by LeeLenaleee**
Remove old unmaintained samples so it cant give any confusion.

### CODE REVIEW

**Review by kurkle — APPROVED** [review]

**Comment by stockiNail** [comment]
Let me ask you, for my lack of experience: why has the milestone been set to 1.2.0 which was already published?

**Comment by kurkle** [comment]
I'd guess because I did not close it when the version was published 😜

**Comment by LeeLenaleee** [comment]
ooh yeah MB just clicked the closest milestone, small mistake :)

**Comment by stockiNail** [comment]
Thank you! I asked because I was thinking that you wanted to update the milestone and I wasn't sure.

**Pull request merged**
