### PR TITLE
Reduce complexity for resolving the label callout position

### PR DESCRIPTION
**Pull request by stockiNail**
This reduces complexity using the enumerated callout position values to check if manageable instead of an if statement with for conditions in OR.

### CODE REVIEW

**Review by kurkle — COMMENTED** [review]
could use `positions.includes`?

**Comment by stockiNail** [comment]
> positions.includes

yes... as usual, forgive my poor knowledge on JS api...

**Comment by stockiNail** [comment]
> > positions.includes
> 
> yes... as usual, forgive my poor knowledge on JS api...

done

**Review by kurkle — APPROVED** [review]
The compressed size change is a little disappointing, but a saved byte is a saved byte :)

| Filename | Size | Change |
| :--- | :---: | :---: |
| `dist/chartjs-plugin-annotation.esm.js` | 15.2 kB | -2 B (0%) |
| `dist/chartjs-plugin-annotation.min.js` | 9.74 kB | -1 B (0%) |

**Pull request merged**
