### PR TITLE
Chart.js < v3.7 warning instead of exception

### PR DESCRIPTION
**Pull request by kurkle**

### CODE REVIEW

**Review by stockiNail — APPROVED** [review]

**Comment by stockiNail** [comment]
I see the CC issue. I don't know how to ignore it.

**Comment by kurkle** [comment]
Just merge. The button is not green but it's not disabled.

**Comment by stockiNail** [comment]
> Or is it disabled for you??

It's disabled for me. Not green

image

**Comment by stockiNail** [comment]
Sorry, I'm wrong. Is not green but enabled. I can merge it.

**Pull request merged**
