### PR TITLE
Enable line annotation using two scales

### PR DESCRIPTION
**Pull request by kurkle**
Changes:

- `position`: 'start', 'end' or 'center'
- alternative xScaleID, yScaleID, xMin, yMin, xMax, yMax options for `line` annotation
- label hit testing by rotating the point (similar to datalabels plugin)
- simpler label position adjustment by calculating the parameter `t` for `pointInLine`

### CODE REVIEW

**Comment by kurkle** [comment]
| Filename | Size | Change |  |
| :--- | :---: | :---: | :---: |
| `dist/chartjs-plugin-annotation.esm.js` | 6.07 kB | -505 B (-8%) | ✅ |
| `dist/chartjs-plugin-annotation.js` | 6.18 kB | -506 B (-8%) | ✅ |
| `dist/chartjs-plugin-annotation.min.js` | 4.17 kB | -447 B (-10%) | 👏 |

@stockiNail take a look, this touches few of the contributions you've made.

**Comment by stockiNail** [comment]
@kurkle thank you very much!
I'm gonna have a look tomorrow.

**Comment by stockiNail** [comment]
@kurkle first feedback:

When the label is rotated an close to boundaries of chart area, the label is cut.,

This was an issue #271 that was solved re-positioning the label.

cut

I'm still testing, more feedbacks in next hours

**Comment by kurkle** [comment]
Thanks @stockiNail, I failed to consider that situation. Current code does move that label down so it fits the chart area. But that can get you only so far:

image

same with this pr: (note the text direction, that might be the next feedback :))

image

In this case, removing the clipping would give a good result, but it does not help if there is no room outside the chart area.
I'm wondering if it would be better to consider this when setting the scale ranges?

**Comment by stockiNail** [comment]
> same with this pr: (note the text direction, that might be the next feedback :))

I have already done :D. See my previous note in the review close to the code.

**Comment by stockiNail** [comment]
> In this case, removing the clipping would give a good result, but it does not help if there is no room outside the chart area.
I'm wondering if it would be better to consider this when setting the scale ranges?

Pr #282 solved this issue recalculating the label position in order to stay inside the chart area.

I know that it's not so simple (that's why I added chart reference into element in that PR).

Removing the cliparea could be configurable in order to address the issue #258 as well, something like that:

```javascript
label: {
	clipEnabled: false, // <-- defaults to true
	position: 'start',
	rotation: -45,
	backgroundColor: 'red',
	content: 'This is a long test label',
	enabled: true
},
```

In this way you can delegate the user to have enough space for the label.

To change the scales limits (as is done now for the values) could be a solution but this could change the chart going to a picture that probably you don't like with additional space in chart area that you want to avoid.
Honestly, I don't like also the current implementation which is changing the min/max of scales when the values are out of scale, therefore we can maintain as is.
If this will be the solution, we must calculate the rotation and then the necessary space for the label before the element drawing is invoked, I guess.

**Comment by stockiNail** [comment]
Other feedback (not so important). All samples are still using the previous `position` option values (left, right, top and bottom).
If it can help, I can submit a PR to your branch, if you don't have time to do it.

**Comment by kurkle** [comment]
> Other feedback (not so important). All samples are still using the previous `position` option values (left, right, top and bottom).
> If it can help, I can submit a PR to your branch, if you don't have time to do it.

Found only one sample using that. And it turs out it does not work correctly with this PR:

pr: (start)
image

master: (top)
image

**Comment by stockiNail** [comment]
@kurkle It seems that `return Math.max(x, y)` (in `calculateTAdjust` method) is wrong because is returning the maximun value instead it should return x (if line is horizontal) and y (if line is vertical)

**Comment by stockiNail** [comment]
Not sure if it could be correct but the return could be

 return w > h ? x : y;

if width of line if greater than height means that the line is horizontal

**Comment by kurkle** [comment]
Last commit solves it like this (test label with long text is `positon: 'end'`:

image

**Comment by stockiNail** [comment]
The commit "Fix calculateTAdjust" doesn't fix the issue. 

fixcjpa

**Comment by kurkle** [comment]
Ok, another try. 

Adjust the label position in 2 phases, first along the line, up to 25% from the desired end, then with slightly modified current method.

image

image

**Comment by kurkle** [comment]
| Filename | Size | Change |
| :--- | :---: | :---: |
| `dist/chartjs-plugin-annotation.esm.js` | 6.61 kB | +35 B (+1%) |
| `dist/chartjs-plugin-annotation.js` | 6.73 kB | +41 B (+1%) |
| `dist/chartjs-plugin-annotation.min.js` | 4.48 kB | -142 B (-3%) |

**Review by etimberg — COMMENTED** [review]
Didn't notice anything wrong. is the change to `start`, `center`, `end` considered breaking?

**Comment by stockiNail** [comment]
@etimberg in my opinion, yes. You don't have errors because if the position is not start or end it will use center, without any issue.
Nevertheless who is using now left, right, top or bottom will have the label in the center, therefore I think it should be considered a breaking change.
Am I wrong?

**Comment by kurkle** [comment]
@etimberg thats the reason I labeled this breaking.

**Comment by stockiNail** [comment]
@kurkle apologize for delay of my feedback but I had other stuff to do it.
But finally I had time to test it and it sounds working correctly!
Thank you very much!

**Review by etimberg — DISMISSED** [review]

**Pull request merged**
