### PR TITLE
New "createElements" method invoked in "beforeUpdate" hook 

### PR DESCRIPTION
**Pull request by stockiNail**
New `createElements` method invoked in `beforeUpdate` hook in order to enable the use of element wherever in the plugin (see PR  #316).

The previous `updateElements` (which created the elements and update them) has been split and now just updates the elements properties called from `afterUpdate` hook.

It reverts part of the PR #323 in order to use again the elements instead of options. This is improving the performance because teh display callback (if present) will be called only once.

### CODE REVIEW

**Comment by stockiNail** [comment]
I have created this PR based on #325 and I know that could create some annoying task to review the code.
Nevertheless this PR makes sense with the other PR implementation.

**Comment by kurkle** [comment]
Commenting the different things happening here:

- Updating the README.md default values
  - I think the update to README.md makes sense. I also think we should have a generic section for things that apply to all elements (like the display), instead of repeating it.
- Creating elements in beforeUpdate
  - Did you try just calling the old `updateElements` from `beforeUpdate`? I think it should work (and should not break any ongoing animations on annotation elements when the chart.update is called)
- Resolving the element defaults
  - Should be ok

**Comment by kurkle** [comment]
> I have created this PR based on #325 and I know that could create some annoying task to review the code.
> Nevertheless this PR makes sense with the other PR implementation.

I see. Please avoid that. These things don't even depend much on each other.

**Comment by stockiNail** [comment]
> Updating the README.md default values
> 
>     * I think the update to README.md makes sense. I also think we should have a generic section for things that apply to all elements (like the display), instead of repeating it.

Fully agree. What do you think to change it in order to go to Chart,js style, with the tables of options instead of the code?
I'm gonna start working on that asap.

> Creating elements in beforeUpdate
> 
>     * Did you try just calling the old `updateElements` from `beforeUpdate`? I think it should work (and should not break any ongoing animations on annotation elements when the chart.update is called)

Yes but it doesn't work because you need `chartArea` object that is available starting form `afterUpdate` hook.

> Resolving the element defaults
> 
>     * Should be ok

That's fine!

**Comment by stockiNail** [comment]
@kurkle rebased. I know that you have already told me to avoid to "extend" another PR.. Really apologize... Let me share with you that I have many things that could be applied here (for instance the callbacks, images in labels content, single instance of context in order that a use can add own options) that I don't write them, I'll forget and I want to have my fork aligned to  the development of main repo.
sorry again.

**Comment by kurkle** [comment]
I'm not a fan of this approach.

How would you feel about storing the merged (and resolved) options into state in `beforeUpdate`, and using those everywhere?
Could also avoid modifying the `options.annotation` when its an object.

**Comment by stockiNail** [comment]
> How would you feel about storing the merged (and resolved) options into state in `beforeUpdate`, and using those everywhere?
> Could also avoid modifying the `options.annotation` when its an object.

Yeah, I agree. That's what I thought at the beginning but I also thought that, when we decided to use the element as part of scriptable context, we have evaluated that the callbacks could consume also other options, owned by element.

You are proposing to use options (merged, resolved and stored into state) instead of elements in the callbacks and wherever is possible instead of element, isn't it?

**Comment by stockiNail** [comment]
> You are proposing to use options (merged, resolved and stored into state) instead of elements in the callbacks and wherever is possible instead of element, isn't it?

@kurkle If yes, I'm gonna start working tomorrow (or the day after tomorrow).

**Comment by kurkle** [comment]
> > You are proposing to use options (merged, resolved and stored into state) instead of elements in the callbacks and wherever is possible instead of element, isn't it?
> 
> @kurkle If yes, I'm gonna start working tomorrow (or the day after tomorrow).

I think I'd add the options as another argument for the callbacks, or stored in the context, not sure yet. I'd still include the element in the context too, when its available. So `callHandler(handler, [{chart, element, options}]);` or `callHandler(handler, [{chart, element}, options]);`, not quite sure yet.

**Comment by stockiNail** [comment]
@kurkle I'd vote for `callHandler(handler, [{chart, element, options}]);`. 
In the meantime if you agree I could try to create new PR (this one sounds being created in the wrong direction) with a possible implementation (shared above) and then you could check if you like it.
Or if you want to do it, I'll wait for that.

**Comment by kurkle** [comment]
> @kurkle I'd vote for `callHandler(handler, [{chart, element, options}]);`.
> In the meantime if you agree I could try to create new PR (this one sounds being created in the wrong direction) with a possible implementation (shared above) and then you could check if you like it.
> Or if you want to do it, I'll wait for that.

I'm quite busy currently, so go ahead if you have the time.

**Comment by stockiNail** [comment]
> I'm quite busy currently, so go ahead if you have the time.

Me too but I promise you I'm gonna do my best.

**Comment by stockiNail** [comment]
Partially addressed by #327. Scriptable options will come by another PR.

**Pull request closed without merging**
