### PR TITLE
Move annotation types handling to types/index.js

### PR DESCRIPTION
**Pull request by kurkle**
As the number of types grow, they deserve their own index.

### CODE REVIEW

**Comment by stockiNail** [comment]
> @stockiNail any thoughts about this change?

yes even if I didn't have the courage to write it ...

It seems your going to expose the annotations in order to enable the custom ones. Or am I completely wrong?

**Comment by kurkle** [comment]
This is a step that would make it easier to allow custom annotation types. I'm still not sure it that is a good solution or if a generic CustomAnnotation would be enough. But that aside, I think this makes the source cleaner. There are also ways (exports in package.json) to indicate these exports are only for internal use.

**Comment by stockiNail** [comment]
I don't have enough skills on javascript packaging to lead that... Sorry.

Nevertheless, with my poor experience, it could be enough to expose the exported helpers functions and the methods of the classes. Nothing more. Maybe I'm wrong but it doesn't seem too dangerous.
But you know better than me other techniques how to isolated some functions. I'm more than happy to follow you and to learn.

About cleanup of the code, I fully agree. I have never asked but is there any guidelines how the code should look like? For instance, the classes on the top and all "private" functions on the bottom?

**Comment by stockiNail** [comment]
Anyway the definition of the interface to extend annotation element is very important, I think.

**Review by etimberg — APPROVED** [review]

**Comment by stockiNail** [comment]
@kurkle I'm going to start for PR to change and continue developing the prototype that I have started last week. Just a matter of time. For sure I'll come back to you.
Before I'd like to close the my open issues and therefore we could have more time to continue thinking how to implement it.

**Pull request merged**
