### PR TITLE
Remove label clipping to box annotation size

### PR DESCRIPTION
**Pull request by stockiNail**
This PR is remove label clipping to box annotation size.

### CODE REVIEW

**Review by LeeLenaleee — APPROVED** [review]

**Comment by stockiNail** [comment]
@LeeLenaleee after merging this one, do you think we will bump to version 2?

**Comment by LeeLenaleee** [comment]
No, I am currently looking into moving project to TS, so if you give me till next week wednesday to see if I can make some progress on it. If I dont have made any progess after that we can merge it, else I want to try and switch to TS first.

Made a quick start on it but need to check things out since types dont match up so its a bit of research work

**Comment by stockiNail** [comment]
> No, I am currently looking into moving project to TS, so if you give me till next week wednesday to see if I can make some progress on it. If I dont have made any progess after that we can merge it, else I want to try and switch to TS first.

No hurry, so take your time.

**Comment by stockiNail** [comment]
I hope to be able to continue contributing in TS because I don't know much about it :pensive:

**Comment by stockiNail** [comment]
@LeeLenaleee I was thinking if it is not better to have a frozen situation before going to TS, merging all pending PR.
This could avoid a double and complex work on those PR

**Comment by LeeLenaleee** [comment]
hmmm yeah I guess, well lets release V2 and make it something for later then

**Comment by stockiNail** [comment]
@LeeLenaleee do you want I try creating bump PR?

**Comment by LeeLenaleee** [comment]
Yeah sure 👍🏻

**Pull request merged**
