### PR TITLE
Bump to version 2.1.1 

### PR DESCRIPTION
**Pull request by stockiNail**
Update dependencies

### CODE REVIEW

**Comment by stockiNail** [comment]
@LeeLenaleee @kurkle what do you think if I will change this PR to bump new version 2.1.1? If yes I will do this evening

**Comment by kurkle** [comment]
> @LeeLenaleee @kurkle what do you think if I will change this PR to bump new version 2.1.1? If yes I will do this evening

Sounds good to me, quick releases is always better.
Maybe it should still include the destroy hook for v3 compatibility though?

**Comment by stockiNail** [comment]
@kurkle @LeeLenaleee not needed because the plugin has the dependency with chartjs 3.7.0 and afterDestroy has been introduced in version 3.7.0

**Comment by stockiNail** [comment]
> Sounds good to me, quick releases is always better.

I have changed version and title of this PR.

**Review by kurkle — APPROVED** [review]

**Review by LeeLenaleee — APPROVED** [review]

**Pull request merged**
