### PR TITLE
Line label font merged with chart.options.font

### LINKED ISSUE #262: Default font of line annotation should be merge with chart.options.font?
With the current line annotation `font` defaults, the `chart.options.font` is ignored.

Maybe the user expectation is if the user changes the font at chart level, this font could be used into the label of line as base configuration, instead of using the `Chart.defaults.font`.

The reference of `Chart.defaults.font` into the line annotation defaults

https://github.com/chartjs/chartjs-plugin-annotation/blob/da07bf955e00523bc8912e5017a36af7cd8c68f9/src/types/line.js#L86-L88

should be removed and the font should be `mergeIf` with `chart.options.font` at runtime.

Make sense?

### PR DESCRIPTION
**Pull request by stockiNail**
Fixes #262 

Line label font merged with `chart.options.font` in order to inherit the chart options instead of `Chart.defaults.font` ones.

### CODE REVIEW

**Comment by kurkle** [comment]
this too needs rebase

**Comment by stockiNail** [comment]
> 
> 
> this too needs rebase

doing.. I need time. Wait for a while.

**Comment by stockiNail** [comment]
rebased

**Comment by kurkle** [comment]
Hmh. Just the sort of things I don't want to have in here. Lets wait with this one (perhaps for https://github.com/chartjs/Chart.js/pull/8008)

**Comment by stockiNail** [comment]
> 
> 
> Hmh. Just the sort of things I don't want to have in here. Lets wait with this one (perhaps for [chartjs/Chart.js#8008](https://github.com/chartjs/Chart.js/pull/8008))

I need to remove this change from the others. I can close this one,

**Pull request closed without merging**
