### PR TITLE
Label fixtures: merge position tests in vertical and horizontal ones

### PR DESCRIPTION
**Pull request by stockiNail**
The percentage position test cases are consolidated in vertical and horizontal ones.
The test case with position and points are removed.

### CODE REVIEW

**Review by kurkle — DISMISSED** [review]
Nice!

Could have ='100%' and ='invalid' in both fixtures for completeness.

**Comment by kurkle** [comment]
Another note, we have some nice looking annotations in tests, maybe some of those should be converted to samples. In tests, the contrast is more important than looks :)

**Comment by stockiNail** [comment]
> we have some nice looking annotations in tests

Which ones are you referring to in particular?

**Comment by kurkle** [comment]
Maybe some of those we are not needing in tests, like label with call-out +point combination. And actually these new fixtures here would be good samples too.

**Comment by stockiNail** [comment]
> Could have ='100%' and ='invalid' in both fixtures for completeness.

added! ;)

**Review by kurkle — APPROVED** [review]

**Comment by stockiNail** [comment]
> Maybe some of those we are not needing in tests, like label with call-out +point combination. And actually these new fixtures here would be good samples too.

I'll have a look following your suggestion and I'll come back with a PR (it also means **PR**oposal in this case).

**Comment by stockiNail** [comment]
Today the testing on Windows sounds to have some issues (always timeout)

```console
[test-*integration]   1) Integration Tests
[test-*integration]        chartjs-plugin-annotation should compile with all supported TS versions:
[test-*integration]      Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. 
[test-*integration]      (D:\a\chartjs-plugin-annotation\chartjs-plugin-annotation\test\integration\integration-test.js)
```

**Pull request merged**
