### PR TITLE
Label: change event tests to inRange tests

### PR DESCRIPTION
**Pull request by stockiNail**
This PR remove events test cases with `inRange` method tests.

### CODE REVIEW

**Comment by stockiNail** [comment]
@kurkle where do we have to move the events' end-2-end test cases?

In my opinion the events' end-2-end test cases must be done. We should share:

1. where?
2. for all annotations types or only 1?

**Comment by kurkle** [comment]
I think for all types and all events, but only for center point for example.

**Comment by stockiNail** [comment]
> OK, let me change this PR with event tests for label.

I had a look and I think it's better to have a specific PR to fix tests on events.

**Review by kurkle — COMMENTED** [review]
I guess the callout is not interactable?

**Review by kurkle — APPROVED** [review]

**Comment by stockiNail** [comment]
> I guess the callout is not interactable?

No, it isn't. Be aware that also arrow heads in line annotation are not interactable. Maybe for arrow heads it could be implemented.

**Pull request merged**
