### PR TITLE
Fix how-to-use guide and put the "annotation" inside options

### PR DESCRIPTION
**Pull request by saeedesmaili**
The "annotation" should be inside the "options", not "plugins", as same as the doc's codepen example.

### CODE REVIEW

**Comment by benmccann** [comment]
It looks like the code in master does read from `options.plugins`, but hasn't been released.

They really should be under `options.plugins`: https://www.chartjs.org/docs/latest/developers/plugins.html#plugin-options

So really the best thing to do is to cut a new release instead. However, I'm not quite sure that it's completely working, so we should probably fix that first: https://github.com/chartjs/chartjs-plugin-annotation/pull/130#issuecomment-474411821

**Comment by rwwagner90** [comment]
Is there any chance that new release will be coming soon?

**Comment by benmccann** [comment]
You could ask on the #dev Slack channel. I've actually never used this plugin and don't have permission to cut a new release

**Comment by rwwagner90** [comment]
@benmccann I am not in the Slack. Could you please ping whoever is in charge of releases?

**Comment by kurkle** [comment]
The correct place for it is in `options.plugins`. This is fixed in the master (Chart.js v3) branch.

**Pull request closed without merging**
