### PR TITLE
Avoid 'Unable to preventDefault inside passive event listener invocation.' message

### PR DESCRIPTION
**Pull request by anxorl**
Avoid 'Unable to preventDefault inside passive event listener invocation.' message.

### CODE REVIEW

**Comment by Techn1x** [comment]
I am getting this as well..

**Comment by benmccann** [comment]
@compwright it looks like this was added in https://github.com/chartjs/chartjs-plugin-annotation/commit/5d14e2632cc956e588a90a5a9ea14d8f171fea2e. Do you know if it's safe to remove?

**Comment by KumarNarendra** [comment]
I am also getting this. My suggestion is, Instead of removing it, we should add `{ passive: false }` to the event.

**Comment by benmccann** [comment]
@KumarNarendra I haven't spent a lot of time understanding this code and haven't worked with passive event listeners before. I agree that `{ passive: false }` would also fix the error, but I'm not sure why one solution would be better than the other. Can you explain why that solution might be preferable?

**Comment by benmccann** [comment]
An alternative fix has been proposed in https://github.com/chartjs/chartjs-plugin-annotation/pull/160. Please take a look and provide feedback as to which is the better approach

**Comment by kurkle** [comment]
The alternative fix was merged

**Pull request closed without merging**
