### PR TITLE
Throw error when non-existing scale id is used

### PR DESCRIPTION
**Pull request by kurkle**
Closes: #468

Updated the Chrome flags so it would not timeout when in background.

### CODE REVIEW

**Review by etimberg — APPROVED** [review]

**Comment by stockiNail** [comment]
@kurkle I think this should be documented. Sorry if I recognized it just now.

**Comment by stockiNail** [comment]
@kurkle maybe I'm wrong but it should be marked as breaking change. I think before the chart was shown anyway.

**Comment by kurkle** [comment]
@stockiNail the issue was marked as bug, so this can be considered to be a bug fix.
Although this could be breaking in some use cases, the annotations did not always show before either (see the issue).

Should be mentioned in the release notes when 1.2 is released, but I'm not sure this needs to be documented. I don't think it was never a valid use case to specify a non-existing scale id for an annotation.

**Comment by stockiNail** [comment]
@kurkle thank you! Agree!

**Comment by stockiNail** [comment]
Sorry @kurkle...  I don't want to boring you, but having a look to the doc (for instance box annotation, https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/types/box.html#configuration), I think the sentence 

_If one of the axes does not match an axis in the chart, the box will take the entire chart dimension._

should be removed. If ok for you, I can do it.

**Comment by kurkle** [comment]
Oh, did not see that. Looks like that actually is a supported use case, so this is a breaking change. I'll deal with it tomorrow.

**Pull request merged**
