### PR TITLE
beforeDraw hook added

### PR DESCRIPTION
**Pull request by elitastic**
Added beforeDraw drawTime hook to fix the gridline issue described in #251

### CODE REVIEW

**Comment by stockiNail** [comment]
@elitastic could you update the README (used as doc page), adding this new configuration?

**Comment by elitastic** [comment]
Readme updated!

**Review by kurkle — APPROVED** [review]

**Comment by stockiNail** [comment]
Thank you very much @elitastic

**Comment by kurkle** [comment]
| Filename | Size | Change |
| :--- | :---: | :---: |
| `dist/chartjs-plugin-annotation.esm.js` | 6.57 kB | +5 B (0%) |
| `dist/chartjs-plugin-annotation.js` | 6.69 kB | +6 B (0%) |
| `dist/chartjs-plugin-annotation.min.js` | 4.62 kB | +5 B (0%) |

**Pull request merged**
