### PR TITLE
Fixes events catching on rotated line labels

### LINKED ISSUE #264: Missed event on line label when rotated
When a line label is rotated, `rotation` not equals to 0, the events on the labels are not correctly caught.
This is because the `labelRect` is storing the coordinates of the rectangle without rotation.  

I'm gonna submit a PR to fix it.

### PR DESCRIPTION
**Pull request by stockiNail**
Fixes #264

### CODE REVIEW

**Comment by kurkle** [comment]
Need to rebase these!

**Comment by stockiNail** [comment]
@kurkle rebased

**Comment by stockiNail** [comment]
> 
> 
> @kurkle rebased

Wait for a while, I'm rebasing again due to PRs merged in the meanwhile.

**Comment by stockiNail** [comment]
> 
> 
> > @kurkle rebased
> 
> Wait for a while, I'm rebasing again due to PRs merged in the meanwhile.

Rebased

**Review by kurkle — APPROVED** [review]

**Pull request merged**
