### PR TITLE
Fix documentation about label annotation and its positioning

### LINKED ISSUE #828: Width for Label annotation doesn't work
I want `label` annotation to take the whole width of the axis, but for some reason, `xMin` and `xMax` values are ignored.
I also tried to use `width` parameter, but it doesn't have any effect either.

In the docs, [there's a line](https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/types/label.html#general) saying that _"To enable to use the box positioning, the `radius` must be set to `0` or `NaN`."_, but could you specify what `radius` it refers to? I wasn't able to find anything for both this plugin or ChartJS itself.

In the example below I used 2 annotations - `box` that can take the whole width of the axis and `label` that doesn't work.

Thank you!

https://jsfiddle.net/ntyv2cdb/17/

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #828 #829

### CODE REVIEW

**Review by LeeLenaleee — APPROVED** [review]

**Comment by LeeLenaleee** [comment]
2.1.2 since there are no enhancements

**Comment by stockiNail** [comment]
> 2.1.2 since there are no enhancements, but I dont really see a need for a bump 🤔

Do you know if release-drafter will change the draft release that it created if in the next days a PR with a enhancement will be merged? I don't release-drafter so well :(

**Comment by LeeLenaleee** [comment]
Yes if a enhancement gets merged it will since the enhancement will also be released

**Comment by stockiNail** [comment]
> Yes if a enhancement gets merged it will since the enhancement will also be released

THANK YOUU!

**Pull request merged**
