### PR TITLE
Add migration guide v2 section to getting started page

### PR DESCRIPTION
**Pull request by stockiNail**
Add migration guide v2 section to getting started page

### CODE REVIEW

**Comment by kurkle** [comment]
While it might not get too long, I think a separate page would be good.

**Comment by stockiNail** [comment]
> While it might not get too long, I think a separate page would be good.

Yes, I thought the same but in CHART.JS the migration guise is inside the Getting started session.
The Getting started plugin is a page and not a group.
 group? separated page from getting started? What would you prefer?

**Comment by LeeLenaleee** [comment]
I think I would place at the bottom of the nav, and then when a V3 comes out we can make it into a seperate sub category where we list each migration

**Comment by stockiNail** [comment]
> I think I would place at the bottom of the nav, and then when a V3 comes out we can make it into a seperate sub category where we list each migration

done!

**Review by kurkle — APPROVED** [review]

**Comment by kurkle** [comment]
Are we ready to move towards v2?

**Comment by stockiNail** [comment]
> Are we ready to move towards v2?

well, good question. I don't see any other enhancement (or bug) to address, in this moment. 
Personally I'm quite busy in this period for a couple of projects but maybe I could find time. Be patient.

And you, what do you think?

**Comment by kurkle** [comment]
> > Are we ready to move towards v2?
> 
> well, good question. I don't see any other enhancement (or bug) to address, in this moment. Personally I'm quite busy in this period for a couple of projects but maybe I could find time. Be patient.
> 
> And you, what do you think?

Quite busy too still, so maybe we should wait for a little more then.

**Comment by stockiNail** [comment]
> Quite busy too still, so maybe we should wait for a little more then.

Agree, I've submitted those PRs in order do not forget what I had in mind (getting old it happens) about implementation.

**Comment by stockiNail** [comment]
> Are we ready to move towards v2?

Shall we start version 2.0 on Apr 4th? 4 weeks after version 1.4.0, make sense?

**Comment by kurkle** [comment]
> > Are we ready to move towards v2?
> 
> Shall we start version 2.0 on Apr 4th? 4 weeks after version 1.4.0, make sense?

Sounds good to me!

**Pull request merged**
