### PR TITLE
eslint fixes

### PR DESCRIPTION
**Pull request by benmccann**
These are fixes suggested by eslint. There was too much to make all the changes and enable eslint all in one PR. Will send a separate PR to enable eslint

The `case` statement formatting seems potentially funny to me, but otherwise the style rules it suggested make sense

### CODE REVIEW

**Comment by simonbrunel** [comment]
do you mean: `case view.mode === horizontalKeyword && view.labelPosition === 'right':`?

**Comment by benmccann** [comment]
I mean that before the `case` statements were indented one level from the `switch` whereas eslint wants them not to be indented. It made more sense to me to have them be indented

**Comment by simonbrunel** [comment]
IMO, this `switch-case` indent level is useless because it increases the line length without making the code more readable since your code will be indented under each `case`.

```javascript
switch (foo) {
	case 0:
		switch (bar) {
			case 0:
				// ...
				break;
			default:
				// ...
				break;
		}
		break;
	default:
		// ...
		break;
}

// - vs -

switch (foo) {
case 0:
	switch (bar) {
	case 0:
		// ...
		break;
	default:
		// ...
		break;
	}
	break;
default:
	// ...
	break;
}
```

**Comment by benmccann** [comment]
I don't have strong feelings. Just wanted to make sure it was something we'd considered and we weren't using a default that we were all against.

Would you be able to merge this PR for me? Thanks!

**Pull request merged**
